# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

   name: Build and Package

   on:
     push:
       branches:
         - master
     pull_request:
       branches:
         - master

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pyinstaller

       - name: Package with PyInstaller
         run: |
           pyinstaller --onefile --windowed --icon=app_icon.ico port_scanner.py

       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
           name: port-scanner
           path: dist/port_scanner
